language: node_js

node_js:
  - "20"

services:
  - docker

install:
  - cd Backend
  - npm ci
  - cd ../FrontEnd
  - npm ci
  - cd ..

script:
  - cd Backend
  - npm test
  - cd ..
  - docker build -t climacolombia-backend ./Backend
  - docker build -t climacolombia-frontend ./FrontEnd

branches:
  only:
    - main